using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Klassd.Workflows.Generators;

/// <summary>
/// Emits a reflection-free constructor factory for every concrete <c>IJob</c> in the compilation, so
/// <c>JobRegistrationBuilder.Add&lt;TJob&gt;()</c> never falls back to <c>ActivatorUtilities</c>. For
/// each job it picks the greediest public constructor (matching <c>ActivatorUtilities</c>' default) and
/// generates <c>new TJob(sp.GetRequiredService&lt;P1&gt;(), …)</c>, registered into
/// <c>GeneratedJobFactories</c> from a <c>[ModuleInitializer]</c> that runs when the job's assembly loads.
/// </summary>
[Generator]
public sealed class JobFactoryGenerator : IIncrementalGenerator
{
    private const string IJobMetadataName = "Klassd.Workflows.Abstractions.IJob";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var jobs = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax or RecordDeclarationSyntax,
                transform: static (ctx, _) => Describe(ctx))
            .Where(static job => job is not null)
            .Select(static (job, _) => job!.Value);

        context.RegisterSourceOutput(jobs.Collect(), static (spc, collected) => Emit(spc, collected));
    }

    /// <summary>A job we can construct: its fully-qualified type and the rendered constructor arguments.</summary>
    private readonly record struct JobInfo(string TypeName, string Arguments);

    private static JobInfo? Describe(GeneratorSyntaxContext ctx)
    {
        if (ctx.SemanticModel.GetDeclaredSymbol(ctx.Node) is not INamedTypeSymbol symbol)
            return null;
        if (symbol.TypeKind != TypeKind.Class || symbol.IsAbstract || symbol.IsStatic || symbol.IsGenericType)
            return null;
        if (!symbol.AllInterfaces.Any(i => i.ToDisplayString() == IJobMetadataName))
            return null;

        // Greediest public instance constructor — the one ActivatorUtilities would pick with no explicit args.
        var ctor = symbol.InstanceConstructors
            .Where(c => c.DeclaredAccessibility == Accessibility.Public)
            .OrderByDescending(c => c.Parameters.Length)
            .FirstOrDefault();
        if (ctor is null)
            return null;

        var args = string.Join(", ", ctor.Parameters.Select(p =>
            $"global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<" +
            $"{p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}>(sp)"));

        return new JobInfo(symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), args);
    }

    private static void Emit(SourceProductionContext spc, ImmutableArray<JobInfo> jobs)
    {
        if (jobs.IsDefaultOrEmpty)
            return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("namespace Klassd.Workflows.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    internal static class JobFactoryModuleInitializer");
        sb.AppendLine("    {");
        sb.AppendLine("        [global::System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine("        internal static void Initialize()");
        sb.AppendLine("        {");
        foreach (var job in jobs.Distinct())
        {
            sb.AppendLine("            global::Klassd.Workflows.Abstractions.GeneratedJobFactories.Register(");
            sb.AppendLine($"                typeof({job.TypeName}),");
            sb.AppendLine($"                static sp => new {job.TypeName}({job.Arguments}));");
        }
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        spc.AddSource("JobFactoryModuleInitializer.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
